openapi: 3.0.0
info:
  description: Сервер авторизации.
  version: "1.0.0"
  title: OAuth2 API
  contact:
    email: ufocomp@gmail.com
externalDocs:
  description: Документация
  url: https://github.com/apostoldevel/module-AuthServer
servers:
  - url: 'https://api.example.com/oauth2'
    description: Production
  - url: 'http://localhost:{port}/oauth2'
    description: Debugging
    variables:
      port:
        enum:
          - '8080'
          - '4977'
          - '3000'
        default: '8080'
tags:
  - name: OAuth2
    description: Сервер авторизации
paths:
  /authorize:
    get:
      tags:
        - OAuth2
      summary: Авторизация.
      parameters:
        - $ref: '#/components/parameters/clientId'
        - $ref: '#/components/parameters/redirectUri'
        - $ref: '#/components/parameters/responseType'
        - $ref: '#/components/parameters/scope'
        - $ref: '#/components/parameters/accessType'
        - $ref: '#/components/parameters/state'
      responses:
        '200':
          description: Redirect to authorize page.
        '400':
          $ref: '#/components/responses/BadRequest'
        '5XX':
          $ref: '#/components/responses/InternalError'
  /token:
    post:
      tags:
        - OAuth2
      summary: Запросить маркер доступа.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/authorization_code'
                - $ref: '#/components/schemas/password'
                - $ref: '#/components/schemas/client_credentials'
                - $ref: '#/components/schemas/refresh_token'
                - $ref: '#/components/schemas/subject_token'
                - $ref: '#/components/schemas/assertion'
      responses:
        '200':
          $ref: '#/components/responses/Ok'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/InternalError'
  /identifier:
    get:
      tags:
        - OAuth2
      summary: Проверить идентификатор пользователя.
      parameters:
        - in: query
          name: value
          required: true
          schema:
            type: string
          description: Идентификатор пользователя (Логин, телефон или адрес электронной почты).
      responses:
        '200':
          description: Успешно.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/identifier'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/InternalError'
components:
  parameters:
    clientId:
      in: query
      name: client_id
      required: true
      schema:
        type: string
        enum: [www-example.com, service-example.com, android-example.com, ios-example.com]
        description: Идентификатор клиента (приложения).
    redirectUri:
      in: query
      name: redirect_uri
      required: true
      schema:
        type: string
        example: http://localhost:8080/docs/oauth2-redirect.html
        format: uri
        description: URI, на который сервер авторизации перенаправит агента пользователя (браузер) и код авторизации.
    responseType:
      in: query
      name: response_type
      required: true
      schema:
        type: string
        enum: [code, token]
        example: code
        description: >
          code: Указывает на то, что приложение запрашивает доступ с помощью кода авторизации.
          token: Приложения JavaScript должны установить значение параметра в token. Это значение указывает серверу авторизации возвращать маркер доступа в виде пары name = value в идентификаторе фрагмента URI (#), на который перенаправляется пользователь после завершения процесса авторизации.
    scope:
      in: query
      name: scope
      required: false
      schema:
        type: string
        description: Список областей, разделенных пробелами, которые определяют ресурсы, к которым ваше приложение может получить доступ от имени пользователя.
    accessType:
      in: query
      name: access_type
      required: false
      schema:
        type: string
        enum: [online, offline]
        description: >
          При `response_type`: code. Указывает, может ли ваше приложение обновлять маркеры доступа, когда пользователь отсутствует в браузере. Допустимые значения параметров: online (по умолчанию) и offline.
    state:
      in: query
      name: state
      required: false
      schema:
        type: string
        description: >
          Набор случайных символов которые будут возвращены сервером клиенту (используется для защиты от повторных запросов).
  responses:
    Ok:
      description: Successfully.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/access_token'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  schemas:
    identifier:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор пользователя.
        username:
          type: string
          description: Имя пользователя (логин).
        name:
          type: string
          description: Наименование пользователя.
        email:
          type: string
          description: Электронной адрес пользователя.
        phone:
          type: string
          description: Телефон пользователя.
        status:
          type: integer
          format: int32
          description: Статус пользователя.
        status_text:
          type: string
          description: Текст статуса пользователя.
        identifiers:
          type: array
          items:
            type: string
            enum: [username, email, phone]
            description: Идентификаторы.
    authorization_code:
      type: object
      description: Код авторизации.
      required:
        - client_id
        - grant_type
        - code
        - redirect_uri
      properties:
        client_id:
          type: string
          description: Идентификатор клиента.
        client_secret:
          type: string
          description: Секрет клиента.
        grant_type:
          type: string
          default: authorization_code
          description: Как определено в спецификации OAuth 2.0, это поле должно содержать значение authorization_code.
        code:
          type: string
          description: Код авторизации, возвращенный из первоначального запроса.
        redirect_uri:
          type: string
          format: uri
          description: >
            URI переадресации (должен совпадать с `redirect_uri` из первоначального запроса).
    password:
      type: object
      description: Учётные данные владельца ресурса.
      required:
        - client_id
        - grant_type
      properties:
        client_id:
          type: string
          description: Идентификатор клиента.
        client_secret:
          type: string
          description: Секрет клиента.
        grant_type:
          type: string
          default: password
          description: Как определено в спецификации OAuth 2.0, это поле должно содержать значение password.
        username:
          type: string
          description: Логин пользователя. Игнорируется если указано значение в поле `secret`.
        password:
          type: string
          description: Пароль пользователя. Игнорируется если указано значение в поле `secret`.
        secret:
          type: string
          description: Секретный код. Если значение указано то поля `username` и `password` заполнять не нужно.
        scope:
          type: string
          description: Список областей, разделенных пробелами, которые определяют ресурсы, к которым ваше приложение может получить доступ от имени пользователя.
    client_credentials:
      type: object
      description: Учётные данные клиента.
      required:
        - client_id
        - grant_type
      properties:
        client_id:
          type: string
          description: Идентификатор клиента.
        client_secret:
          type: string
          description: Секрет клиента.
        grant_type:
          type: string
          default: client_credentials
          description: Как определено в спецификации OAuth 2.0, это поле должно содержать значение client_credentials.
        scope:
          type: string
          description: Список областей, разделенных пробелами, которые определяют ресурсы, к которым ваше приложение может получить доступ от имени пользователя.
    refresh_token:
      type: object
      description: Обновление маркера доступа.
      required:
        - client_id
        - grant_type
        - refresh_token
      properties:
        client_id:
          type: string
          description: Идентификатор клиента.
        client_secret:
          type: string
          description: Секрет клиента.
        grant_type:
          type: string
          default: refresh_token
          description: Как определено в спецификации OAuth 2.0, это поле должно содержать значение refresh_token.
        refresh_token:
          type: string
          description: Маркер обновления, выданный ранее.
        scope:
          type: string
          description: Список областей, разделенных пробелами, которые определяют ресурсы, к которым ваше приложение может получить доступ от имени пользователя.
    subject_token:
      type: object
      description: Грант на продление.
      required:
        - client_id
        - grant_type
        - subject_token
      properties:
        client_id:
          type: string
          description: Идентификатор клиента.
        client_secret:
          type: string
          description: Секрет клиента.
        grant_type:
          type: string
          default: urn:ietf:params:oauth:grant-type:token-exchange
          description: Как определено в спецификации OAuth 2.0, это поле должно содержать значение urn:ietf:params:oauth:grant-type:token-exchange.
        subject_token:
          type: string
          description: Маркер, выданный ранее.
        subject_token_type:
          type: string
          description: >
            Тип передаваемого маркера. Доступные значения: urn:ietf:params:oauth:token-type:jwt (по умолчанию), urn:ietf:params:oauth:token-type:access_token, urn:ietf:params:oauth:token-type:refresh_token, urn:ietf:params:oauth:token-type:id_token.
        scope:
          type: string
          description: Список областей, разделенных пробелами, которые определяют ресурсы, к которым ваше приложение может получить доступ от имени пользователя.
    assertion:
      type: object
      description: Использование маркера JWT в качестве гранта авторизации.
      required:
        - client_id
        - grant_type
        - assertion
      properties:
        client_id:
          type: string
          description: Идентификатор клиента.
        client_secret:
          type: string
          description: Секрет клиента.
        grant_type:
          type: string
          default: urn:ietf:params:oauth:grant-type:jwt-bearer
          description: Как определено в спецификации OAuth 2.0, это поле должно содержать значение urn:ietf:params:oauth:grant-type:jwt-bearer.
        assertion:
          type: string
          description: Маркер JWT выданный другой (внешней) системой.
        scope:
          type: string
          description: Список областей, разделенных пробелами, которые определяют ресурсы, к которым ваше приложение может получить доступ от имени пользователя.
    access_token:
      type: object
      description: Маркер доступа.
      required:
        - access_token
        - token_type
        - expires_in
        - session
      properties:
        access_token:
          type: string
          description: Маркер краткосрочного доступа (сроком действия 1 час).
        token_type:
          type: string
          default: Bearer
          description: Тип возвращаемого маркера. Значение всегда будет Bearer.
        expires_in:
          type: integer
          format: int32
          default: 3600
          description: Оставшееся время жизни маркера доступа в секундах.
        session:
          type: string
          description: Идентификатор сессии пользователя.
        refresh_token:
          type: string
          description: Маркер который вы можете использовать для получения нового маркер доступа.
        id_token:
          type: string
          description: Маркер пользователя.
    response:
      type: object
      required:
        - code
        - message
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
    error:
      type: object
      required:
        - error
        - error_description
      properties:
        error:
          type: string
        error_description:
          type: string
  securitySchemes:
    oauth2:
      type: oauth2
      description: >
        This API uses OAuth 2 with the implicit grant flow.
        [More info](https://github.com/apostoldevel/module-AuthServer).
      flows:
        password:
          tokenUrl: /oauth2/token
          scopes:
            https://dev.example.com: development
            https://demo.example.com: demo
            serp: default
        implicit:
          authorizationUrl: /oauth2/authorize
          scopes:
            https://dev.example.com: development
            https://demo.example.com: demo
            serp: default
security:
  - oauth2:
      - https://api.example.com
      - example
