[Interface]
PrivateKey = *
Address = 10.0.0.2/24
ListenPort = 51820
PostUp = /config/postup.sh
PostDown = iptables -t nat -F; iptables -F

[Peer]
PublicKey = *
AllowedIPs = 10.0.0.1/32
Endpoint = 1.2.3.4:51820
PersistentKeepalive = 25
