#!/usr/bin/env bash

set -e

PROJECT_NAME=apostol-crm
BUILD_TYPE=Release
INSTALL_PATH=/usr/sbin

pop_directory()
{
    popd >/dev/null
}

push_directory()
{
    local DIRECTORY="$1"

    pushd "$DIRECTORY" >/dev/null
}

display_heading_message()
{
    echo
    echo "********************** $@ **********************"
    echo
}

display_message()
{
    echo "$@"
}

display_error()
{
    >&2 echo "$@"
}

display_help()
{
    display_message "Usage: ./deploy [OPTION]..."
    display_message "Script options:"
    display_message "  --build-dir=<path>       Location of build files (default: cmake-build-{type})."
    display_message "  --release                Release build (default)."
    display_message "  --debug                  Debug build."
    display_message "  --update                 Skip rebuild, just deploy binary."
    display_message "  --help                   Display this help."
    display_message ""
}

display_configuration()
{
    display_message "Configuration."
    display_message "--------------------------------------------------------------------"
    display_message "PROJECT_NAME         : $PROJECT_NAME"
    display_message "BUILD_TYPE           : $BUILD_TYPE"
    display_message "BUILD_DIR            : $BUILD_DIR"
    display_message "--------------------------------------------------------------------"
}

make_project()
{
    display_heading_message "Build: $PROJECT_NAME"

    cmake --build "$BUILD_DIR" --parallel $(nproc)
}

update_project()
{
    display_heading_message "Deploy $PROJECT_NAME"

    display_heading_message "stop service $PROJECT_NAME"
    systemctl stop $PROJECT_NAME.service

    display_heading_message "install $PROJECT_NAME"
    cmake --install "$BUILD_DIR"

    display_heading_message "clear log files..."
    rm -rf /etc/$PROJECT_NAME/logs/*.log

    display_heading_message "start service $PROJECT_NAME"
    systemctl start ${PROJECT_NAME}.service
}

# Parse command line options
for OPTION in "$@"; do
    case $OPTION in
        (--help)                DISPLAY_HELP="yes";;
        (--release)             BUILD_TYPE="Release";;
        (--debug)               BUILD_TYPE="Debug";;
        (--update)              BUILD_UPDATE="yes";;
        (--build-dir=*)         BUILD_DIR="${OPTION#*=}";;
    esac
done

if ! [[ $BUILD_DIR ]]; then
  if [[ $BUILD_TYPE == Debug ]]; then
    BUILD_DIR=cmake-build-debug
  else
    BUILD_DIR=cmake-build-release
  fi
fi

if [[ $DISPLAY_HELP ]]; then
    display_help
else
    display_configuration

    if ! [[ $BUILD_UPDATE ]]; then
        make_project
    fi

    update_project
fi
