[default]
host=smtp.mail-server.com:465
username=mail@example.com
password=$SMTP_PASSWORD_INFO

[info]
host=smtp.mail-server.com:465
username=mail@example.com
password=$SMTP_PASSWORD_INFO

[noreply]
host=smtp.mail-server.com:465
username=mail@example.com
password=$SMTP_PASSWORD_NOREPLY

[support]
host=smtp.mail-server.com:465
username=mail@example.com
password=$SMTP_PASSWORD_SUPPORT
