\echo [M] Updating configuration...

\echo [M] call admin
\ir './admin/update.psql'

\echo [M] call entity
\ir './entity/update.psql'

\echo [M] call priority
\ir './priority/update.psql'

\echo [M] call api
\ir './api/update.psql'

\echo [M] call api
\ir './report/update.psql'

\echo [M] call observer
\ir './observer/update.psql'

\echo [M] call 'confirmation'
\ir './confirmation/update.psql'

\echo [M] call routine.sql
\ir routine.sql
