\echo [M] call table.sql
\ir table.sql

\ir './name/create.psql'

\echo [M] call view.sql
\ir view.sql

\echo [M] call exception.sql
\ir exception.sql

\echo [M] call routine.sql
\ir routine.sql

\echo [M] call api.sql
\ir api.sql

\echo [M] call rest.sql
\ir rest.sql

\echo [M] call event.sql
\ir event.sql

\echo [M] call init.sql
\ir init.sql

\echo [M] call report.sql
\ir report.sql

\ir './employee/create.psql'
\ir './customer/create.psql'
